name: tools_continuous_delivery

on:
  push:
    branches:
      - main
    paths:
      - 'src/promptflow-tools/**'
      - '!README.*'
      - '!src/promptflow-tools/tests/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch name'
        required: true
        default: 'main'
        type: string
      is_candidate_release:
        description: 'Whether it is a candidate release'
        required: true
        default: false
        type: boolean

jobs:
  main_branch_release:
    if: github.event_name == 'push'
    uses: ./.github/workflows/wheel_distributing.yml
    name: Private PyPI main branch release
    with:
      ReleaseType: "Release"
      UploadAsLatest: "False"
      SourceFolderName: "promptflow-tools"
      ConfigsFolderPath: "scripts/distributing/configs"
    secrets: inherit
  
  non_main_branch_release:
    if: github.event_name == 'workflow_dispatch' && !inputs.is_candidate_release
    uses: ./.github/workflows/wheel_distributing.yml
    name: Private PyPI non-main branch release
    with:
      ReleaseType: "Test"
      UploadAsLatest: "False"
      SourceFolderName: "promptflow-tools"
      ConfigsFolderPath: "scripts/distributing/configs"
    secrets: inherit
  
  # private pypi candidate release asks for approval.
  approve_candidate_release:
    if: github.event_name == 'workflow_dispatch' && inputs.is_candidate_release
    runs-on: ubuntu-latest
    name: Approve manual release
    permissions:
      issues: write
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.TOKEN }}
          approvers: 16oeahr,chjinche,DaweiCai
          minimum-approvals: 1
          issue-title: "Request to release new promptflow-tools candidate version."

  candidate_release:
    needs: approve_candidate_release
    uses: ./.github/workflows/wheel_distributing.yml
    name: Private PyPI candidate release
    with:
      ReleaseType: "Release"
      UploadAsLatest: "True"
      SourceFolderName: "promptflow-tools"
      ConfigsFolderPath: "scripts/distributing/configs"
      IsCandidateRelease: "True"
    secrets: inherit
